[package]
name = "siggen_toolkit"
version = "0.1.0"
authors = ["Bradley Hutchinson <inukage0029@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
structopt = "0.3"
reqwest = {version = "0.11", features = ["blocking"]}
eframe = "0.15"